services:
  # --- Identity Database For Keycloak ---
  doorlist_keycloak_db:
    image: postgres:16
    container_name: doorlist_keycloak_db
    env_file:
      - dev.env
    restart: unless-stopped
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: ${Doorlist_KC_DB_USER}
      POSTGRES_PASSWORD: ${Doorlist_KC_DB_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - doorlist_keycloak_db:/var/lib/postgresql/data
    networks:
      - doorlist_services
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${Doorlist_KC_DB_USER} -d keycloak"] # 
      interval: 5s
      timeout: 5s
      retries: 5

  # --- Application Database For Doorlist Backend
  doorlist_app_db:
    image: postgres:16
    container_name: doorlist_app_db
    env_file:
      - dev.env
    environment:
      POSTGRES_DB: doorlist_app
      POSTGRES_USER: ${Doorlist_App_DB_USER}
      POSTGRES_PASSWORD: ${Doorlist_App_DB_PASSWORD}
      
      # Feed the Infrastructure root to the API. 
      # DOORLIST_INFRA_PATH: ${PWD} # WORK ON ME
    ports:
      - "5434:5432"
    volumes:
      - doorlist_app_db:/var/lib/postgresql/data
    networks:
      - doorlist_services
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${Doorlist_App_DB_USER} -d doorlist_app"]
      # test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
  
  doorlist_keycloak:
    image: keycloak/keycloak:26.1
    container_name: doorlist_keycloak_server
    env_file:
      - dev.env
    command: start-dev --import-realm --features=dpop
    restart: unless-stopped
    depends_on:
      doorlist_keycloak_db:
        condition: service_healthy
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://doorlist_keycloak_db:5432/keycloak
      KC_DB_USERNAME: ${Doorlist_KC_DB_USER}
      KC_DB_PASSWORD: ${Doorlist_KC_DB_PASSWORD}
      
      KC_HOSTNAME: localhost
      KC_HOSTNAME_PORT: 8443
      KC_HOSTNAME_STRICT: "false"
      KC_HTTP_ENABLED: "true"
      
      KEYCLOAK_ADMIN: ${Doorlist_KC_ADMIN_USER}
      KEYCLOAK_ADMIN_PASSWORD: ${Doorlist_KC_ADMIN_PASSWORD}
      KC_HTTPS_CERTIFICATE_FILE: /opt/keycloak/certs/doorlist.keycloak.dev.crt
      KC_HTTPS_CERTIFICATE_KEY_FILE: /opt/keycloak/certs/doorlist.keycloak.dev.key

      KC_SPI_THEME_STATIC_MAX_AGE: "-1"
      KC_SPI_THEME_CACHE_THEMES: "false"
      KC_SPI_THEME_CACHE_TEMPLATES: "false"
    volumes:
      # Theme
      - ./Keycloak/themes/doorlist:/opt/keycloak/themes/doorlist

      # SSL
      - ./certs/doorlist.keycloak.dev.crt:/opt/keycloak/certs/doorlist.keycloak.dev.crt
      - ./certs/doorlist.keycloak.dev.key:/opt/keycloak/certs/doorlist.keycloak.dev.key

      # Realm config
      - ./Keycloak/realm-export.keycloak.dev.json:/opt/keycloak/data/import/realm-export.json
    ports:
      - "8080:8080"
      - "8443:8443"
    networks:
      - doorlist_services
     
    healthcheck:
      test: ["CMD-SHELL", "exec 3<>/dev/tcp/127.0.0.1/8443 && echo -e 'GET /health/ready HTTP/1.1\\r\\nHost: localhost\\r\\n\\r\\n' >&3 && close 3"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  doorlist_keycloak_db:
  doorlist_app_db:

networks:
  doorlist_services:
    driver: bridge
